version: "3.5"

services:
  db:
    image: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "docker"
      POSTGRES_USER: "postgres"
      POSTGRES_DATABASE: "gostack_gobarber"
